### ISSUE TITLE
raml-dotnet-tools 可用性研究

### ISSUE THREAD

**Issue by fs7744** [CodeBabyBear/AriesDoc#1]
https://github.com/mulesoft-labs/raml-dotnet-tools 这个工具使用的可用性研究

**Comment by xcyf008** [comment]
这不是一个完整的工具么

**Comment by xcyf008** [comment]
提取RAMA [https://github.com/mulesoft-labs/raml-dotnet-tools#metadata-extract-a-raml-definition-from-your-web-app](url)

**Comment by fs7744** [comment]
@xcyf008 必须嵌入代码吗？必须访问host server吗？所有api都在一个页面吗？

**Comment by xcyf008** [comment]
还没有看到其他使用方式
